// Configuration client — reflète shared/sources.js (source de vérité pour le sync serveur).
// Modifier une source ici n'affecte QUE l'affichage de la page "Sources" ;
// pour changer ce qui est réellement synchronisé, éditez shared/sources.js.
window.APP_CONFIG = {
  APPLICATIONS: [
    "Dairy", "Beverage", "Bakery", "Confectionery", "Savoury",
    "Ice Cream", "Sauces", "Snacks", "Nutrition", "Other"
  ],
  TRENDS: [
    "Ube", "Pandan", "Matcha", "Protein", "Healthy", "Botanical",
    "Natural", "NOLO", "Hard Seltzer", "Functional", "Plant-Based",
    "Premium", "Tropical", "Exotic"
  ],
  MARKETS: [
    "Tunisia", "Algeria", "Morocco", "Egypt", "Côte d'Ivoire",
    "Senegal", "Libya", "Africa", "Europe", "USA", "Asia", "International"
  ],
  AFRICA_MARKETS: [
    "Tunisia", "Algeria", "Morocco", "Egypt", "Côte d'Ivoire",
    "Senegal", "Libya", "Africa"
  ],
  SOURCES: [
    { id: "foodbev", name: "FoodBev Media", url: "https://www.foodbev.com", category: "Food & Beverage", country: "International" },
    { id: "foodnavigator", name: "FoodNavigator", url: "https://www.foodnavigator.com", category: "Food & Beverage", country: "Europe" },
    { id: "foodingredientsfirst", name: "Food Ingredients First", url: "https://www.foodingredientsfirst.com", category: "Ingredients", country: "International" },
    { id: "ingredientsnetwork", name: "Ingredients Network", url: "https://www.ingredientsnetwork.com", category: "Ingredients", country: "International" },
    { id: "innova", name: "Innova Market Insights", url: "https://www.innovamarketinsights.com", category: "Innovation / Trends", country: "International" },
    { id: "mintel", name: "Mintel", url: "https://www.mintel.com", category: "Consumer / Trends", country: "International" },
    { id: "beveragedaily", name: "BeverageDaily", url: "https://www.beveragedaily.com", category: "Beverage", country: "Europe" },
    { id: "bevnet", name: "BevNET", url: "https://www.bevnet.com", category: "Beverage", country: "USA" },
    { id: "dairyreporter", name: "DairyReporter", url: "https://www.dairyreporter.com", category: "Dairy", country: "Europe" },
    { id: "bakeryandsnacks", name: "BakeryAndSnacks", url: "https://www.bakeryandsnacks.com", category: "Bakery", country: "Europe" },
    { id: "confectionerynews", name: "ConfectioneryNews", url: "https://www.confectionerynews.com", category: "Confectionery", country: "Europe" },
    { id: "perfumerflavorist", name: "Perfumer & Flavorist", url: "https://www.perfumerflavorist.com", category: "Flavors", country: "USA" },
    { id: "foodbusinessnews", name: "Food Business News", url: "https://www.foodbusinessnews.net", category: "Food Industry", country: "USA" },
    { id: "justfood", name: "Just Food", url: "https://www.just-food.com", category: "FMCG / Food Industry", country: "International" },
    { id: "nutraingredients", name: "NutraIngredients", url: "https://www.nutraingredients.com", category: "Nutrition / Functional", country: "Europe" },
    { id: "fooddive", name: "Food Dive", url: "https://www.fooddive.com", category: "Food Industry", country: "USA" },
    { id: "vegconomist", name: "vegconomist (Food & Beverage)", url: "https://vegconomist.com/category/food-and-beverage/", category: "Plant-Based / Food & Beverage", country: "International" },
    { id: "foodbusinessafrica", name: "Food Business Africa", url: "https://www.foodbusinessafrica.com", category: "Food & Beverage — Africa", country: "Africa" },
    { id: "foodsafetyafrica", name: "Food Safety Africa", url: "https://www.foodsafetyafrica.net", category: "Food Safety — Africa", country: "Africa" },
    { id: "fbreporter", name: "Food & Beverage Reporter (South Africa)", url: "https://fbreporter.co.za", category: "Food & Beverage — Southern Africa", country: "Africa" },
    { id: "howwemadeitinafrica", name: "How We Made It In Africa", url: "https://www.howwemadeitinafrica.com", category: "African Business", country: "Africa" },
    { id: "bevindustry", name: "Beverage Industry", url: "https://www.bevindustry.com", category: "Beverage", country: "USA" }
  ],
  MANUAL_LINKS: [
    { name: "Food Business Africa — LinkedIn", url: "https://www.linkedin.com/company/food-business-africa-official-page", note_fr: "Actualités food/beverage/milling Afrique", note_en: "Africa food/beverage/milling news" },
    { name: "Innova Market Insights — LinkedIn", url: "https://www.linkedin.com/company/innova-market-insights", note_fr: "Tendances marché mondial (source sur abonnement)", note_en: "Global market trends (subscription source)" },
    { name: "Mintel — LinkedIn", url: "https://www.linkedin.com/company/mintel", note_fr: "Tendances consommateur mondial (source sur abonnement)", note_en: "Global consumer trends (subscription source)" },
    { name: "How We Made It In Africa — LinkedIn", url: "https://www.linkedin.com/company/how-we-made-it-in-africa", note_fr: "Entrepreneuriat africain", note_en: "African entrepreneurship" }
  ],
  TREND_TYPES: [
    "Flavor Trend", "Beverage Industry Trend", "Consumer Trend",
    "Format & Packaging", "Innovation Opportunity", "Local Market Opportunity", "Manufacturing Trend"
  ],

  CONSUMER_DRIVERS: [
    { id: "accessibility", name: "Accessibility", desc_fr: "Prix / affordability", desc_en: "Price / affordability", weight: 9 },
    { id: "convenience", name: "Convenience", desc_fr: "Praticité / RTD", desc_en: "Convenience / RTD", weight: 8 },
    { id: "functionality", name: "Functionality", desc_fr: "Hydratation / énergie / wellness", desc_en: "Hydration / energy / wellness", weight: 8 },
    { id: "premium", name: "Premium Experience", desc_fr: "Qualité / expérience", desc_en: "Quality / experience", weight: 7 },
    { id: "local", name: "Local Identity", desc_fr: "Culture / ingrédients locaux", desc_en: "Culture / local ingredients", weight: 7 },
    { id: "occasion", name: "Occasion", desc_fr: "Moment de consommation", desc_en: "Consumption moment", weight: 6 },
    { id: "discovery", name: "Discovery", desc_fr: "Nouvelles expériences", desc_en: "New experiences", weight: 5 }
  ],

  // Contenu éditorial stratégique — évaluations qualitatives Aromatech,
  // PAS des statistiques de marché officielles.
  BEVERAGE_TRENDS: [
    {
      id: "premiumisation",
      num: "01",
      name: "Affordable Premiumisation",
      name_fr: "Premiumisation accessible",
      trendType: "Beverage Industry Trend",
      status: "Growing",
      desc_fr: "La premiumisation ne disparaît pas sous la pression économique : elle devient plus sélective. Les consommateurs acceptent de payer plus pour une meilleure expérience lors d'occasions sociales, tout en réduisant d'autres dépenses.",
      desc_en: "Premiumisation isn't disappearing under economic pressure — it's becoming more selective. Consumers accept paying more for a better experience during social occasions, while cutting back elsewhere.",
      consumerDriver: "Premium Experience",
      applications: ["Premium soft drinks", "Mocktails", "Premium juices", "Flavored waters", "RTD teas", "Energy drinks"],
      regionalRelevance: "High — urban middle class across major African markets",
      opportunity_fr: "Créer des produits \"Affordable Premium\" qui améliorent saveur, packaging et présentation sans basculer dans le luxe.",
      opportunity_en: "Create \"Affordable Premium\" products that elevate flavor, packaging and presentation without moving into luxury territory.",
      flavors: ["Blood Orange", "Yuzu", "Kumquat", "Lychee", "Orange Blossom", "Pistachio", "Botanical blends"],
      strategicQuestion_fr: "Comment créer une perception premium sans rendre le produit inaccessible ?",
      strategicQuestion_en: "How to create a premium perception without making the product inaccessible?",
      scoring: { market: "High", african: "High", flavor: "Very High", innovation: "High", premium: "Very High", cross: "High" },
      overallScore: "HIGH"
    },
    {
      id: "functional",
      num: "02",
      name: "Functional Beverages",
      name_fr: "Boissons fonctionnelles",
      trendType: "Consumer Trend",
      status: "Growing",
      desc_fr: "Les consommateurs attendent de plus en plus de leurs boissons qu'elles apportent autre chose que le rafraîchissement : hydratation, énergie, récupération, bien-être, digestion.",
      desc_en: "Consumers increasingly expect their beverages to deliver more than refreshment: hydration, energy, recovery, wellbeing, digestion.",
      consumerDriver: "Functionality",
      applications: ["Functional waters", "RTD teas", "Energy drinks", "Wellness shots", "Fortified juices"],
      regionalRelevance: "High — growing wellness awareness in urban centers",
      opportunity_fr: "Ne pas copier les tendances wellness internationales : identifier des ingrédients et profils déjà familiers aux consommateurs africains.",
      opportunity_en: "Don't just copy international wellness trends: identify ingredients and profiles already familiar to African consumers.",
      flavors: ["Ginger", "Hibiscus", "Mint", "Citrus", "Coconut", "Botanical profiles"],
      strategicQuestion_fr: "Comment associer fonctionnalité perçue et familiarité locale ?",
      strategicQuestion_en: "How to combine perceived functionality with local familiarity?",
      scoring: { market: "High", african: "High", flavor: "High", innovation: "High", premium: "Medium", cross: "High" },
      overallScore: "HIGH"
    },
    {
      id: "rtd",
      num: "03",
      name: "Ready-to-Drink Everywhere",
      name_fr: "Le \"Ready-to-Drink\" partout",
      trendType: "Format & Packaging",
      status: "Established",
      desc_fr: "Les formats RTD continuent de se développer dans le café, le thé, les cocktails, les energy drinks et les boissons fonctionnelles. La praticité devient un facteur important de choix.",
      desc_en: "RTD formats continue expanding across coffee, tea, cocktails, energy drinks and functional beverages. Convenience is becoming a key purchase driver.",
      consumerDriver: "Convenience",
      applications: ["RTD Coffee", "RTD Tea", "Energy drinks", "Functional drinks", "Mocktails"],
      regionalRelevance: "Medium-High — driven by rapid urbanization; price remains decisive",
      opportunity_fr: "L'urbanisation rapide rend les formats RTD intéressants, mais le prix reste un facteur déterminant.",
      opportunity_en: "Rapid urbanization makes RTD formats attractive, but price remains a determining factor.",
      flavors: ["Mango", "Berry", "Ginger", "Coffee"],
      strategicQuestion_fr: "Quels formats RTD peuvent trouver leur marché au-delà des consommateurs urbains premium ?",
      strategicQuestion_en: "Which RTD formats can find a market beyond premium urban consumers?",
      scoring: { market: "High", african: "Medium", flavor: "Medium", innovation: "Medium", premium: "Medium", cross: "High" },
      overallScore: "MEDIUM"
    },
    {
      id: "occasion",
      num: "04",
      name: "Purpose-Built / Occasion-Based Drinks",
      name_fr: "Boissons pensées pour une occasion",
      trendType: "Innovation Opportunity",
      status: "Emerging",
      desc_fr: "Le marché évolue de \"quel goût voulez-vous ?\" vers \"à quel moment allez-vous consommer cette boisson ?\" : morning energy, work break, workout, recovery, socializing, relaxation, refreshment.",
      desc_en: "The market is shifting from \"what flavor do you want?\" to \"when will you drink this?\": morning energy, work break, workout, recovery, socializing, relaxation, refreshment.",
      consumerDriver: "Occasion",
      applications: ["Morning energy drinks", "Post-workout recovery", "Social drinks", "Evening relaxation drinks"],
      regionalRelevance: "Medium — emerging concept, strongest in urban lifestyle segments",
      opportunity_fr: "Créer des boissons associées à une occasion de consommation claire plutôt qu'à un simple profil aromatique.",
      opportunity_en: "Create beverages tied to a clear consumption occasion rather than just a flavor profile.",
      flavors: ["Citrus/Ginger (morning)", "Lime/Mint (refreshment)", "Mango/Berry/Lychee (social)", "Botanical/Floral (relaxation)", "Cocoa/Milk Tea (indulgence)"],
      strategicQuestion_fr: "Comment construire une gamme cohérente autour des moments de consommation ?",
      strategicQuestion_en: "How to build a coherent range around consumption moments?",
      scoring: { market: "Medium", african: "Medium", flavor: "High", innovation: "Very High", premium: "Medium", cross: "High" },
      overallScore: "MEDIUM"
    },
    {
      id: "local-modern",
      num: "05",
      name: "Local Ingredients, Modern Positioning",
      name_fr: "Ingrédients locaux, positionnement moderne",
      trendType: "Local Market Opportunity",
      status: "Opportunity",
      desc_fr: "L'Afrique dispose déjà d'une vaste bibliothèque d'ingrédients : sorgho, hibiscus, baobab, tamarin, gingembre, kola, cacao, café. L'enjeu est de les repositionner via un branding contemporain, un packaging moderne et de nouveaux formats.",
      desc_en: "Africa already has a vast library of ingredients: sorghum, hibiscus, baobab, tamarind, ginger, kola, cocoa, coffee. The challenge is repositioning them through contemporary branding, modern packaging and new formats.",
      consumerDriver: "Local Identity",
      applications: ["Premium soft drinks", "RTD teas", "Craft sodas", "Functional drinks"],
      regionalRelevance: "Very High — differentiation lever unique to African markets",
      opportunity_fr: "Local ingredients + modern positioning = African differentiation.",
      opportunity_en: "Local ingredients + modern positioning = African differentiation.",
      flavors: ["Sorghum", "Hibiscus", "Baobab", "Tamarind", "Ginger", "Kola", "Cocoa", "Coffee"],
      strategicQuestion_fr: "Comment donner une crédibilité premium à des ingrédients locaux sans perdre leur authenticité ?",
      strategicQuestion_en: "How to give local ingredients premium credibility without losing authenticity?",
      scoring: { market: "Medium", african: "Very High", flavor: "Very High", innovation: "High", premium: "High", cross: "High" },
      overallScore: "VERY HIGH"
    },
    {
      id: "small-formats",
      num: "06",
      name: "Smaller, More Flexible Formats",
      name_fr: "Formats plus petits et plus flexibles",
      trendType: "Format & Packaging",
      status: "Established",
      desc_fr: "Le format devient un outil stratégique : un petit format réduit le prix d'entrée, facilite l'achat impulsif, augmente l'accessibilité et maintient une perception premium.",
      desc_en: "Format becomes a strategic tool: a smaller format lowers the entry price, facilitates impulse buying, increases accessibility and maintains a premium perception.",
      consumerDriver: "Accessibility",
      applications: ["Small PET", "Cans", "Single serve", "Mini premium formats", "Sachets / concentrates"],
      regionalRelevance: "Very High — price-per-purchase matters more than price-per-litre",
      opportunity_fr: "Trouver le bon prix d'entrée plutôt que simplement le bon prix au litre.",
      opportunity_en: "Find the right entry price rather than simply the right price per litre.",
      flavors: [],
      strategicQuestion_fr: "Quel est le bon prix d'entrée plutôt que simplement le bon prix au litre ?",
      strategicQuestion_en: "What is the right entry price rather than simply the right price per litre?",
      scoring: { market: "Very High", african: "Very High", flavor: "Low", innovation: "Medium", premium: "Medium", cross: "Medium" },
      overallScore: "HIGH"
    },
    {
      id: "nolo",
      num: "07",
      name: "No & Low Alcohol",
      name_fr: "No & Low Alcohol",
      trendType: "Consumer Trend",
      status: "Emerging",
      desc_fr: "La recherche de modération crée de nouvelles opportunités autour des boissons sans alcool ou faiblement alcoolisées — à explorer aussi sous l'angle botanical, functional et adult soft drinks.",
      desc_en: "The search for moderation creates new opportunities around no/low alcohol beverages — also worth exploring through botanical, functional and adult soft drink angles.",
      consumerDriver: "Discovery",
      applications: ["Botanical beverages", "Functional beverages", "Premium soft drinks", "Mocktails", "Adult soft drinks"],
      regionalRelevance: "Medium — nascent but growing in urban premium segments",
      opportunity_fr: "Créer une expérience premium et sociale sans dépendre de l'alcool.",
      opportunity_en: "Create a premium, social experience without relying on alcohol.",
      flavors: ["Hibiscus", "Ginger", "Citrus", "Mint", "Botanicals", "Tropical fruits"],
      strategicQuestion_fr: "Comment créer une expérience premium et sociale sans dépendre de l'alcool ?",
      strategicQuestion_en: "How to create a premium, social experience without relying on alcohol?",
      scoring: { market: "Medium", african: "Medium", flavor: "High", innovation: "High", premium: "High", cross: "Medium" },
      overallScore: "MEDIUM"
    },
    {
      id: "cold-coffee",
      num: "08",
      name: "RTD & Cold Coffee",
      name_fr: "RTD & Cold Coffee",
      trendType: "Innovation Opportunity",
      status: "Growing",
      desc_fr: "Le café se développe sous des formats froids : cold brew, iced coffee, RTD coffee, café aromatisé. L'Afrique possède un avantage particulier : pays producteurs de café + urbanisation croissante.",
      desc_en: "Coffee is expanding into cold formats: cold brew, iced coffee, RTD coffee, flavored coffee. Africa has a particular advantage: coffee-producing countries + growing urbanization.",
      consumerDriver: "Discovery",
      applications: ["RTD Coffee", "Iced Coffee", "Cold Brew", "Coffee + Milk", "Flavored Coffee"],
      regionalRelevance: "High — strong in coffee-producing African markets",
      opportunity_fr: "Capitaliser sur l'avantage des pays producteurs de café combiné à l'urbanisation croissante.",
      opportunity_en: "Capitalize on the advantage of coffee-producing countries combined with growing urbanization.",
      flavors: ["Vanilla", "Caramel", "Cocoa", "Condensed Milk", "Pistachio", "Coconut"],
      strategicQuestion_fr: "Comment capter la demande urbaine tout en valorisant le café local ?",
      strategicQuestion_en: "How to capture urban demand while showcasing local coffee?",
      scoring: { market: "Medium", african: "High", flavor: "High", innovation: "Medium", premium: "High", cross: "Medium" },
      overallScore: "HIGH"
    },
    {
      id: "lifestyle",
      num: "09",
      name: "Beverage Brands as Lifestyle Platforms",
      name_fr: "Les marques de boissons deviennent des plateformes lifestyle",
      trendType: "Consumer Trend",
      status: "Growing",
      desc_fr: "Les grandes marques ne vendent plus uniquement une boisson : elles construisent une identité, une communauté, une expérience. Football, musique, festivals et gaming deviennent des leviers d'engagement.",
      desc_en: "Major brands no longer sell just a drink: they build identity, community, experience. Football, music, festivals and gaming become engagement levers.",
      consumerDriver: "Local Identity",
      applications: ["Sponsored events", "Music/artist collaborations", "Limited editions", "Community campaigns"],
      regionalRelevance: "Very High — music, sport and culture are powerful in African markets",
      opportunity_fr: "S'appuyer sur la puissance de la musique locale, le sport, les artistes et les événements.",
      opportunity_en: "Leverage the power of local music, sport, artists and events.",
      flavors: [],
      strategicQuestion_fr: "What does the brand stand for beyond the liquid?",
      strategicQuestion_en: "What does the brand stand for beyond the liquid?",
      scoring: { market: "High", african: "Very High", flavor: "Low", innovation: "Medium", premium: "High", cross: "Medium" },
      overallScore: "HIGH"
    },
    {
      id: "local-production",
      num: "10",
      name: "Local Production & Manufacturing",
      name_fr: "Production locale & manufacturing",
      trendType: "Manufacturing Trend",
      status: "Growing",
      desc_fr: "Le développement de capacités de production locales réduit la dépendance aux importations, rapproche la production des consommateurs et améliore les supply chains.",
      desc_en: "Developing local production capacity reduces reliance on imports, brings production closer to consumers and improves supply chains.",
      consumerDriver: "Accessibility",
      applications: ["Local bottling", "Regional supply chains", "Local ingredient sourcing"],
      regionalRelevance: "Very High — structural, industry-wide relevance",
      opportunity_fr: "La production locale peut devenir un avantage compétitif.",
      opportunity_en: "Local production can become a competitive advantage.",
      flavors: [],
      strategicQuestion_fr: "Comment la proximité de production peut-elle accélérer l'adaptation aux marchés locaux ?",
      strategicQuestion_en: "How can production proximity accelerate adaptation to local markets?",
      scoring: { market: "High", african: "Very High", flavor: "Low", innovation: "Medium", premium: "Low", cross: "Medium" },
      overallScore: "HIGH"
    }
  ],

  FLAVOR_INDUSTRY_MATRIX: [
    { trend: "Functional Beverages", flavors: ["Ginger", "Hibiscus", "Mint", "Citrus"] },
    { trend: "Affordable Premium", flavors: ["Blood Orange", "Yuzu", "Lychee", "Botanicals"] },
    { trend: "RTD", flavors: ["Mango", "Berry", "Ginger", "Coffee"] },
    { trend: "Purpose-Built", flavors: ["Citrus", "Ginger", "Coconut", "Botanicals"] },
    { trend: "Local Ingredients", flavors: ["Hibiscus", "Baobab", "Tamarind", "Kola"] },
    { trend: "No & Low Alcohol", flavors: ["Hibiscus", "Ginger", "Citrus", "Mint"] },
    { trend: "Cold Coffee", flavors: ["Vanilla", "Cocoa", "Caramel", "Pistachio"] },
    { trend: "Lifestyle", flavors: ["Tropical", "Local Heritage", "Signature blends"] }
  ],

  AROMATECH_OPPORTUNITIES: [
    { id: "heritage", num: "01", title_fr: "Local Heritage", title_en: "Local Heritage", desc_fr: "Identifier et moderniser les profils africains.", desc_en: "Identify and modernize African flavor profiles." },
    { id: "functional-flavor", num: "02", title_fr: "Functional Flavor", title_en: "Functional Flavor", desc_fr: "Développer des profils adaptés aux boissons wellness et fonctionnelles.", desc_en: "Develop profiles suited to wellness and functional beverages." },
    { id: "premium-accessible", num: "03", title_fr: "Premium Accessible", title_en: "Premium Accessible", desc_fr: "Créer des profils premium mais accessibles.", desc_en: "Create premium yet accessible profiles." },
    { id: "occasion-innovation", num: "04", title_fr: "Occasion-Based Innovation", title_en: "Occasion-Based Innovation", desc_fr: "Développer les saveurs autour des moments de consommation.", desc_en: "Develop flavors around consumption moments." },
    { id: "rtd-flavor", num: "05", title_fr: "RTD", title_en: "RTD", desc_fr: "Identifier les profils adaptés aux formats prêts à boire.", desc_en: "Identify profiles suited to ready-to-drink formats." },
    { id: "local-global", num: "06", title_fr: "Local × Global", title_en: "Local × Global", desc_fr: "Combiner une saveur internationale avec une signature locale.", desc_en: "Combine an international flavor with a local signature.",
      examples: ["Hibiscus × Citrus", "Ginger × Lime", "Mango × Ginger", "Coconut × Pineapple", "Matcha × Pistachio", "Mint × Orange Blossom"] }
  ],

  AFRICA_FLAVOR_LIBRARY: [
    { id: "sorghum", name: "Sorghum", desc_fr: "Céréale traditionnelle largement cultivée en Afrique, base de nombreuses boissons fermentées locales.", desc_en: "Traditional cereal widely grown across Africa, base of many local fermented beverages.", countries: ["Africa"] },
    { id: "hibiscus", name: "Hibiscus", desc_fr: "Fleur acidulée utilisée en infusion (bissap), très présente en Afrique de l'Ouest.", desc_en: "Tart flower used in infusions (bissap), very present in West Africa.", countries: ["Senegal", "Africa"] },
    { id: "baobab", name: "Baobab", desc_fr: "Fruit riche en vitamine C, saveur acidulée, symbole de l'arbre emblématique africain.", desc_en: "Vitamin-C rich fruit with a tangy flavor, symbol of the iconic African tree.", countries: ["Africa"] },
    { id: "tamarind", name: "Tamarind", desc_fr: "Pulpe aigre-douce très utilisée dans les boissons et sauces d'Afrique du Nord et de l'Ouest.", desc_en: "Sweet-sour pulp widely used in North and West African drinks and sauces.", countries: ["Morocco", "Algeria", "Africa"] },
    { id: "ginger", name: "Ginger", desc_fr: "Racine piquante emblématique, base du \"ginger drink\" populaire dans toute l'Afrique de l'Ouest.", desc_en: "Iconic spicy root, base of the \"ginger drink\" popular across West Africa.", countries: ["Africa"] },
    { id: "kola", name: "Kola", desc_fr: "Noix stimulante traditionnelle, racine historique du positionnement \"cola\" mondial.", desc_en: "Traditional stimulant nut, historic root of the global \"cola\" positioning.", countries: ["Africa"] },
    { id: "cocoa", name: "Cocoa", desc_fr: "Afrique de l'Ouest = premier bassin de production mondial, opportunité de valorisation locale.", desc_en: "West Africa is the world's top cocoa-producing region — a local value-add opportunity.", countries: ["Côte d'Ivoire", "Africa"] },
    { id: "coffee", name: "Coffee", desc_fr: "Éthiopie et l'Afrique de l'Est en particulier, terroir historique du café mondial.", desc_en: "Ethiopia and East Africa in particular — the historic terroir of world coffee.", countries: ["Africa"] }
  ],

  // ==========================================================================
  // AFRICA FLAVOR TRENDS 2026 — rapport éditorial (onglet "Flavor Trends 2026")
  // Structure volontairement plate et simple : pour ajouter une tendance,
  // ajouter un objet à FLAVOR_TRENDS_2026 ci-dessous, rien d'autre à modifier.
  // ==========================================================================
  FLAVOR_TRENDS_2026_KPIS: [
    { icon: "🌿", label: "Botanical" },
    { icon: "🍊", label: "Citrus" },
    { icon: "🥛", label: "Dairy" },
    { icon: "🌶️", label: "Spicy" },
    { icon: "✨", label: "Premium" }
  ],

  FLAVOR_TRENDS_2026: [
    { name: "Hibiscus", category: "Beverage", region: "West Africa", countries: ["Nigeria", "Senegal"], applications: ["RTD teas", "Carbonated juices", "Functional beverages"], positioning: "Botanical / Refreshment", localName: "Bissap / Zobo" },
    { name: "Mint", category: "Beverage", region: "North Africa", countries: ["Tunisia", "Algeria", "Morocco"], applications: ["Green tea", "Energy drinks", "Flavored water"], positioning: "Botanical / Refreshment" },
    { name: "Orange Blossom", category: "Beverage", region: "North Africa", countries: ["Tunisia", "Algeria", "Morocco"], applications: ["Green tea", "Energy drinks", "Flavored water"], positioning: "Botanical / Refreshment" },
    { name: "Ginger", category: "Beverage", region: "West Africa", countries: ["Nigeria", "Côte d'Ivoire"], applications: ["RTD", "Functional beverages", "Mocktails"], positioning: "Freshness / Functional perception" },
    { name: "Lime", category: "Beverage", region: "West Africa", countries: ["Nigeria", "Côte d'Ivoire"], applications: ["RTD", "Functional beverages", "Mocktails"], positioning: "Freshness / Functional perception" },
    { name: "Yuzu", category: "Beverage", region: "North Africa", countries: ["Egypt", "Morocco"], applications: ["Premium juices", "Mocktails", "Functional beverages"], positioning: "Sophisticated citrus / Premium alternative" },
    { name: "Kumquat", category: "Beverage", region: "North Africa", countries: ["Egypt", "Morocco"], applications: ["Premium juices", "Mocktails", "Functional beverages"], positioning: "Sophisticated citrus / Premium alternative" },
    { name: "Blood Orange", category: "Beverage", region: "North Africa", countries: ["Egypt", "Morocco"], applications: ["Premium juices", "Mocktails", "Functional beverages"], positioning: "Sophisticated citrus / Premium alternative" },
    { name: "Cocoa", category: "Beverage", region: "International", countries: ["Africa"], applications: ["RTD", "Milk tea", "Indulgent drinks"], positioning: "Evening indulgence / Urban consumption" },
    { name: "Strawberry", category: "Dairy", region: "International", countries: ["Africa"], applications: ["Flavored milk", "Drinking yogurt", "UHT dairy"], positioning: "Volume driver / Affordable / Mass market" },
    { name: "Banana", category: "Dairy", region: "International", countries: ["Africa"], applications: ["Flavored milk", "Drinking yogurt", "UHT dairy"], positioning: "Volume driver / Affordable / Mass market" },
    { name: "Honey", category: "Dairy", region: "North Africa", countries: ["Tunisia", "Algeria", "Egypt"], applications: ["Premium yogurt", "Laban", "Spoonable yogurt"], positioning: "Cultured & fermented / Premium" },
    { name: "Date", category: "Dairy", region: "North Africa", countries: ["Tunisia", "Algeria", "Egypt"], applications: ["Premium yogurt", "Laban", "Spoonable yogurt"], positioning: "Cultured & fermented / Premium" },
    { name: "Matcha", category: "Dairy", region: "International", countries: ["Africa"], applications: ["Dairy desserts", "Ice cream", "Premium yogurt"], positioning: "Upscale / Premium / Indulgent" },
    { name: "Pistachio", category: "Dairy", region: "International", countries: ["Africa"], applications: ["Dairy desserts", "Ice cream", "Premium yogurt"], positioning: "Upscale / Premium / Indulgent" },
    { name: "Harissa", category: "Savory", region: "North Africa", countries: ["Tunisia", "Algeria"], applications: ["Chips", "Crackers", "Seasonings"], positioning: "Heritage spice / Regional identity", localName: "Piment • Ail • Cumin" },
    { name: "Preserved Lemon", category: "Savory", region: "North Africa", countries: ["Tunisia", "Morocco"], applications: ["Seasonings", "Savory bakery"], positioning: "Heritage / Tangy fermented" },
    { name: "Za'atar", category: "Savory", region: "North Africa", countries: ["Egypt", "Tunisia"], applications: ["Savory bakery", "Seasonings"], positioning: "Herbal / Toasted" },
    { name: "Dukkah", category: "Savory", region: "North Africa", countries: ["Egypt"], applications: ["Snacks", "Seasonings"], positioning: "Nutty / Spiced" },
    { name: "Suya", category: "Savory", region: "West Africa", countries: ["Nigeria"], applications: ["Chips", "Popcorn", "Instant noodles", "Bouillons"], positioning: "Street food / Convenience food", localName: "Yaji — Peanut • Ginger • Chili" },
    { name: "Jollof", category: "Savory", region: "West Africa", countries: ["Nigeria", "Senegal", "Côte d'Ivoire"], applications: ["Instant noodles", "Bouillons", "Ready-to-eat meals"], positioning: "Regional icon / Smoked tomato base" },
    { name: "Smoked Fish", category: "Savory", region: "West Africa", countries: ["Nigeria", "Senegal"], applications: ["Bouillons", "Ready-to-eat meals", "Seasonings"], positioning: "Smoky / Seafood / Umami" },
    { name: "Intense Chili", category: "Savory", region: "West Africa", countries: ["Nigeria", "Côte d'Ivoire"], applications: ["Chips", "Popcorn", "Instant noodles"], positioning: "Habanero / Scotch Bonnet / Heat" }
  ],

  FLAVOR_2026_APPLICATIONS: [
    "Beverage", "Dairy", "Ice Cream", "Bakery", "Snacks", "Instant Noodles", "Seasoning", "RTD", "Mocktails"
  ],

  FLAVOR_2026_OVERVIEW: [
    { title: "Botanical Refreshment", items: ["Hibiscus", "Mint", "Orange Blossom"] },
    { title: "Intense Citrus", items: ["Ginger", "Lime", "Blood Orange", "Yuzu", "Kumquat"] },
    { title: "Fruit & Exotic", items: ["Tropical fruits", "Exotic fruit combinations"] },
    { title: "Cultured & Creamy", items: ["Strawberry", "Banana", "Honey", "Date", "Pistachio", "Matcha"] },
    { title: "Regional Spice", items: ["Harissa", "Suya", "Jollof", "Za'atar", "Dukkah"] },
    { title: "Indulgent & Premium", items: ["Cocoa", "Milk Tea", "Pistachio", "Rich creamy profiles"] }
  ],

  FLAVOR_2026_REGIONS: [
    {
      id: "north-africa", title: "North Africa",
      countries: [{ flag: "🇹🇳", name: "Tunisia" }, { flag: "🇩🇿", name: "Algeria" }, { flag: "🇲🇦", name: "Morocco" }, { flag: "🇱🇾", name: "Libya" }, { flag: "🇪🇬", name: "Egypt" }],
      trends: ["Mint", "Orange Blossom", "Harissa", "Date", "Honey", "Citrus", "Pistachio"],
      strongCategories: "Beverage botanicals, dairy indulgence, savory heritage spices",
      applications: "RTD tea, premium yogurt, savory bakery, seasonings"
    },
    {
      id: "west-africa", title: "West Africa",
      countries: [{ flag: "🇳🇬", name: "Nigeria" }, { flag: "🇸🇳", name: "Senegal" }, { flag: "🇨🇮", name: "Côte d'Ivoire" }],
      trends: ["Hibiscus", "Ginger", "Lime", "Suya", "Jollof", "Chili", "Smoked Fish"],
      strongCategories: "Functional beverages, street-food snacking, bouillons",
      applications: "RTD/functional drinks, chips, popcorn, instant noodles, bouillons"
    }
  ],

  FLAVOR_2026_OPPORTUNITIES: [
    { icon: "🌿", title: "Local Botanicals", desc_fr: "Transformer les ingrédients emblématiques locaux en profils modernes.", desc_en: "Turn iconic local ingredients into modern flavor profiles." },
    { icon: "🍊", title: "Premium Citrus", desc_fr: "Développer des agrumes plus sophistiqués et différenciants.", desc_en: "Develop more sophisticated, differentiated citrus profiles." },
    { icon: "🌶️", title: "Heritage Spices", desc_fr: "Moderniser les profils culinaires traditionnels dans les snacks et convenience food.", desc_en: "Modernize traditional culinary profiles for snacks and convenience food." },
    { icon: "✨", title: "Affordable Premium", desc_fr: "Créer des expériences premium accessibles grâce à des associations de saveurs différenciantes.", desc_en: "Create accessible premium experiences through differentiated flavor pairings." }
  ],

  FLAVOR_2026_AROMATECH_ANGLE: [
    { num: "01", title: "Inspire", desc_fr: "Identifier les tendances émergentes avant leur massification.", desc_en: "Spot emerging trends before they go mainstream." },
    { num: "02", title: "Localize", desc_fr: "Adapter les profils internationaux aux préférences régionales africaines.", desc_en: "Adapt international profiles to regional African preferences." },
    { num: "03", title: "Innovate", desc_fr: "Transformer les tendances culinaires en concepts produits.", desc_en: "Turn culinary trends into product concepts." },
    { num: "04", title: "Accelerate", desc_fr: "Proposer rapidement des prototypes et applications aux industriels.", desc_en: "Quickly deliver prototypes and applications to manufacturers." }
  ],

  FLAVOR_2026_SOURCES: [
    { name: "Mordor Intelligence", url: "https://www.mordorintelligence.com" },
    { name: "Allied Market Research", url: "https://www.alliedmarketresearch.com" },
    { name: "Food Ingredients First", url: "https://www.foodingredientsfirst.com" },
    { name: "Innova Market Insights", url: "https://www.innovamarketinsights.com" },
    { name: "IFT", url: "https://www.ift.org" },
    { name: "Research and Markets", url: "https://www.researchandmarkets.com" }
  ],

  I18N: {
    fr: {
      navHome: "Home", navFlavorTrends: "Flavor Trends", navBeverageTrends: "Beverage Trends",
      navFlavorLibrary: "African Flavor Library", navCountry: "Country View",
      navOpportunities: "Opportunities", navShortlist: "My Shortlist", navSources: "Sources",
      navDashboard: "Dashboard", navLatest: "Latest Innovations", navTrends: "Trend Radar",
      navIow: "Innovation of the Week", navAfrica: "Africa Focus",
      bevTrendsTitle: "Africa Beverage Trends 2026",
      bevTrendsSubtitle: "Beyond flavor: the forces reshaping Africa's beverage industry",
      bevTrendsIntro: "Les consommateurs africains attendent désormais davantage de leurs boissons : accessibilité, qualité, praticité, fonctionnalité et identité locale. L'enjeu n'est plus simplement d'identifier les tendances mondiales, mais de déterminer lesquelles ont un véritable potentiel en Afrique.",
      consumerDrivers: "Consumer Drivers", trendType: "Trend Type",
      applications: "Applications", regionalRelevance: "Regional relevance", opportunity: "Innovation opportunity",
      strategicQuestion: "Strategic question", flavorConnection: "Flavor connection",
      scoringTitle: "Strategic Priority", overallScore: "Score global",
      matrixTitle: "Flavor × Industry Trend Matrix", matrixHint: "Cliquez sur une tendance pour voir les saveurs associées",
      aromatechTitle: "What This Means for Aromatech Africa",
      finalInsight1: "Les consommateurs demandent désormais davantage à leurs boissons : plus d'accessibilité sans sacrifier la qualité, plus de praticité sans perdre l'expérience, et plus d'identité locale sans paraître dépassé.",
      finalInsight2: "L'enjeu n'est pas de suivre toutes les tendances mondiales. Il est d'identifier celles qui ont réellement du sens pour l'Afrique et de les adapter aux consommateurs locaux.",
      flavorLibraryTitle: "Africa's Untapped Flavor Library",
      flavorLibrarySub: "Ingrédients locaux, repositionnement moderne",
      countryViewTitle: "Country View", countryViewSub: "Sélectionnez un marché pour filtrer innovations et tendances",
      selectCountry: "Sélectionner un pays", allAfrica: "Toute l'Afrique",
      shortlistTitle: "My Shortlist", shortlistSub: "Vos innovations et tendances sauvegardées",
      shortlistEmpty: "Aucun élément sauvegardé pour l'instant. Cliquez sur ☆ sur une card pour l'ajouter.",
      addToShortlist: "Ajouter à ma shortlist", removeFromShortlist: "Retirer de ma shortlist",
      scoringNote: "Ces scores sont une évaluation stratégique indicative, pas des statistiques officielles du marché.",
      level1: "QUOI ?", level2: "OÙ ?", level3: "ET ALORS ?",

      navFlavorReport: "Flavor Trends 2026",
      frTitle: "AFRICA FLAVOR TRENDS 2026",
      frSubtitle: "Les tendances de saveurs qui façonnent l'industrie agroalimentaire africaine",
      frTagline: "Aromatech Afrique · Tunisie | Algérie | Afrique · 2026",
      frHeroText: "Les consommateurs africains recherchent désormais des expériences gustatives qui combinent plaisir, identité locale, fonctionnalité et premiumisation.",
      frNavOverview: "Overview", frNavBeverages: "Beverages", frNavDairy: "Dairy", frNavSavory: "Savory", frNavMap: "Regional Map", frNavOpportunities: "Opportunities",
      frOverviewTitle: "Africa Flavor Landscape 2026",
      frBeverageTitle: "01 — Beverage Flavors", frBeverageSub: "Botanical Refreshment & Intense Citrus",
      frDairyTitle: "02 — Dairy Flavors", frDairySub: "Cultured Sourness & Fruit Staples",
      frSavoryTitle: "03 — Savory Flavors", frSavorySub: "Regional Spice Blends & Intense Heat",
      frFormulationInsight: "Les profils vanille et lait concentré jouent également un rôle important dans les formulations laitières d'Afrique de l'Ouest, notamment pour renforcer la perception de richesse et de gourmandise.",
      frSuyaSpotlight: "🔥 TREND SPOTLIGHT",
      frSuyaQuote: "Un profil emblématique d'Afrique de l'Ouest qui transpose les codes de la street food dans les catégories snacks et convenience food.",
      frMapTitle: "Regional Flavor Map", frMapHint: "Survolez une région pour voir ses tendances",
      frMatrixTitle: "Flavor × Application Matrix", frMatrixHint: "Cliquez sur une saveur pour voir ses applications",
      frOppTitle: "Flavor Opportunities for Africa",
      frAromatechTitle: "What does this mean for Aromatech?",
      frCta: "Explore Flavor Opportunities →",
      frSourcesTitle: "Sources & References",
      frFooterTagline: "Flavoring solutions • Innovation • Market Insights",
      applications2026: "Applications", positioning: "Positioning", markets2026: "Markets", localNameLabel: "Nom local",
      manualLinksTitle: "Liens de référence (consultation manuelle)",
      manualLinksNote: "LinkedIn ne propose plus de flux RSS depuis 2013 — ces liens ne sont donc pas synchronisés automatiquement, à consulter manuellement.",

      navClientWatch: "Veille Clients", navCompetitorWatch: "Veille Concurrents",
      watchAddTitle: "Ajouter une entreprise à surveiller",
      watchNamePlaceholder: "Nom de l'entreprise", watchUrlPlaceholder: "Site web (https://…)",
      watchFeedPlaceholder: "Flux RSS (optionnel, sinon détection auto)",
      watchAddBtn: "Ajouter", watchRemoveBtn: "Retirer",
      watchStatusActive: "Actif (RSS détecté)", watchStatusManual: "Accès manuel", watchStatusWarning: "Avertissement", watchStatusPending: "En attente",
      watchEmpty: "Aucune entreprise ajoutée pour l'instant.",
      watchLastCheck: "Dernière vérification", watchNoItems: "Aucun article récent détecté.",
      watchAutoDiscoveryNote: "À l'ajout, le système essaie de détecter automatiquement un flux RSS sur le site. Si aucun flux n'est trouvé, l'entreprise passe en \"Accès manuel\" — vous pouvez alors consulter le site directement via le lien.",
      watchStandaloneNote: "Dans ce document de consultation autonome, les entreprises ajoutées sont sauvegardées localement dans votre navigateur, mais la détection RSS et la synchronisation réelles nécessitent le projet Netlify déployé.",
      searchPlaceholder: "Rechercher une innovation…",
      syncNow: "SYNC NOW", syncing: "Synchronisation…",
      lastSync: "Dernière synchronisation", never: "jamais",
      statTotal: "Total innovations", stat24h: "Nouveautés 24h", stat7d: "Nouveautés 7 jours", statSources: "Sources surveillées",
      filterApp: "Application", filterTrend: "Tendance", filterMarket: "Marché", filterDate: "Date",
      all: "Toutes", today: "Aujourd'hui", last7: "7 derniers jours", last30: "30 derniers jours", last90: "3 derniers mois",
      viewSource: "Voir la source", newBadge: "NOUVEAU",
      noResults: "Aucune innovation ne correspond à ces filtres.",
      iowTitle: "Innovation of the Week", iowWhy: "Pourquoi c'est intéressant",
      africaTitle: "Africa Focus", africaSub: "Innovations pertinentes pour les marchés africains",
      oppTitle: "Market Opportunities", oppSub: "Lecture marketing indicative — non commerciale",
      sourcesTitle: "Sources surveillées", colSource: "Source", colCategory: "Catégorie", colCountry: "Pays", colStatus: "Statut", colLastSync: "Dernier sync",
      dashTitle: "Innovation Radar", dashSub: "Veille marketing automatisée",
      trendTitle: "Trending Now"
    },
    en: {
      navHome: "Home", navFlavorTrends: "Flavor Trends", navBeverageTrends: "Beverage Trends",
      navFlavorLibrary: "African Flavor Library", navCountry: "Country View",
      navOpportunities: "Opportunities", navShortlist: "My Shortlist", navSources: "Sources",
      navDashboard: "Dashboard", navLatest: "Latest Innovations", navTrends: "Trend Radar",
      navIow: "Innovation of the Week", navAfrica: "Africa Focus",
      bevTrendsTitle: "Africa Beverage Trends 2026",
      bevTrendsSubtitle: "Beyond flavor: the forces reshaping Africa's beverage industry",
      bevTrendsIntro: "African consumers now expect more from their beverages: accessibility, quality, convenience, functionality and local identity. The challenge is no longer just spotting global trends, but determining which ones have real potential in Africa.",
      consumerDrivers: "Consumer Drivers", trendType: "Trend Type",
      applications: "Applications", regionalRelevance: "Regional relevance", opportunity: "Innovation opportunity",
      strategicQuestion: "Strategic question", flavorConnection: "Flavor connection",
      scoringTitle: "Strategic Priority", overallScore: "Overall score",
      matrixTitle: "Flavor × Industry Trend Matrix", matrixHint: "Click a trend to see its associated flavors",
      aromatechTitle: "What This Means for Aromatech Africa",
      finalInsight1: "Consumers now demand more from their beverages: more accessibility without sacrificing quality, more convenience without losing the experience, and more local identity without feeling outdated.",
      finalInsight2: "The challenge isn't to follow every global trend. It's to identify the ones that truly make sense for Africa and adapt them to local consumers.",
      flavorLibraryTitle: "Africa's Untapped Flavor Library",
      flavorLibrarySub: "Local ingredients, modern repositioning",
      countryViewTitle: "Country View", countryViewSub: "Select a market to filter innovations and trends",
      selectCountry: "Select a country", allAfrica: "All Africa",
      shortlistTitle: "My Shortlist", shortlistSub: "Your saved innovations and trends",
      shortlistEmpty: "Nothing saved yet. Click ☆ on a card to add it.",
      addToShortlist: "Add to shortlist", removeFromShortlist: "Remove from shortlist",
      scoringNote: "These scores are an indicative strategic assessment, not official market statistics.",
      level1: "WHAT?", level2: "WHERE?", level3: "SO WHAT?",

      navFlavorReport: "Flavor Trends 2026",
      frTitle: "AFRICA FLAVOR TRENDS 2026",
      frSubtitle: "The flavor trends shaping Africa's food & beverage industry",
      frTagline: "Aromatech Afrique · Tunisia | Algeria | Africa · 2026",
      frHeroText: "African consumers are now looking for taste experiences that combine pleasure, local identity, functionality and premiumisation.",
      frNavOverview: "Overview", frNavBeverages: "Beverages", frNavDairy: "Dairy", frNavSavory: "Savory", frNavMap: "Regional Map", frNavOpportunities: "Opportunities",
      frOverviewTitle: "Africa Flavor Landscape 2026",
      frBeverageTitle: "01 — Beverage Flavors", frBeverageSub: "Botanical Refreshment & Intense Citrus",
      frDairyTitle: "02 — Dairy Flavors", frDairySub: "Cultured Sourness & Fruit Staples",
      frSavoryTitle: "03 — Savory Flavors", frSavorySub: "Regional Spice Blends & Intense Heat",
      frFormulationInsight: "Vanilla and condensed milk profiles also play an important role in West African dairy formulations, reinforcing the perception of richness and indulgence.",
      frSuyaSpotlight: "🔥 TREND SPOTLIGHT",
      frSuyaQuote: "An iconic West African profile that brings street food codes into the snacks and convenience food categories.",
      frMapTitle: "Regional Flavor Map", frMapHint: "Hover a region to see its trends",
      frMatrixTitle: "Flavor × Application Matrix", frMatrixHint: "Click a flavor to see its applications",
      frOppTitle: "Flavor Opportunities for Africa",
      frAromatechTitle: "What does this mean for Aromatech?",
      frCta: "Explore Flavor Opportunities →",
      frSourcesTitle: "Sources & References",
      frFooterTagline: "Flavoring solutions • Innovation • Market Insights",
      applications2026: "Applications", positioning: "Positioning", markets2026: "Markets", localNameLabel: "Local name",
      manualLinksTitle: "Reference links (manual check)",
      manualLinksNote: "LinkedIn has offered no RSS feed since 2013 — these links are not auto-synced, check them manually.",

      navClientWatch: "Client Watch", navCompetitorWatch: "Competitor Watch",
      watchAddTitle: "Add a company to watch",
      watchNamePlaceholder: "Company name", watchUrlPlaceholder: "Website (https://…)",
      watchFeedPlaceholder: "RSS feed (optional, auto-detected otherwise)",
      watchAddBtn: "Add", watchRemoveBtn: "Remove",
      watchStatusActive: "Active (RSS found)", watchStatusManual: "Manual access", watchStatusWarning: "Warning", watchStatusPending: "Pending",
      watchEmpty: "No company added yet.",
      watchLastCheck: "Last check", watchNoItems: "No recent article detected.",
      watchAutoDiscoveryNote: "When added, the system tries to auto-detect an RSS feed on the site. If none is found, the company is marked \"Manual access\" — you can then check the site directly via the link.",
      watchStandaloneNote: "In this standalone preview document, added companies are saved locally in your browser, but real RSS detection and syncing require the deployed Netlify project.",
      searchPlaceholder: "Search innovations…",
      syncNow: "SYNC NOW", syncing: "Syncing…",
      lastSync: "Last synchronization", never: "never",
      statTotal: "Total innovations", stat24h: "New 24h", stat7d: "New 7 days", statSources: "Sources monitored",
      filterApp: "Application", filterTrend: "Trend", filterMarket: "Market", filterDate: "Date",
      all: "All", today: "Today", last7: "Last 7 days", last30: "Last 30 days", last90: "Last 3 months",
      viewSource: "View source", newBadge: "NEW",
      noResults: "No innovation matches these filters.",
      iowTitle: "Innovation of the Week", iowWhy: "Why it matters",
      africaTitle: "Africa Focus", africaSub: "Innovations relevant to African markets",
      oppTitle: "Market Opportunities", oppSub: "Indicative marketing read — non-commercial",
      sourcesTitle: "Sources Monitored", colSource: "Source", colCategory: "Category", colCountry: "Country", colStatus: "Status", colLastSync: "Last Sync",
      dashTitle: "Innovation Radar", dashSub: "Automated marketing intelligence",
      trendTitle: "Trending Now"
    }
  }
};
